apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voting-app
  labels:
    app: vote
  name: vote-blue

spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

  replicas: 1

  selector:
    matchLabels:
      app: vote
      color: blue

  template:
    metadata:
      labels:
        app: vote
        color: blue

    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - vote

      securityContext:
        runAsUser: 33
        runAsGroup: 33
        runAsNonRoot: true

      automountServiceAccountToken: false
      serviceAccountName: vote-sa

      containers:
        - image: azam92/voting-app-vote:52dff781a5b3fd89248bdc59c0bf8df6af4666d4
          name: vote-blue

          ports:
            - containerPort: 8080
              name: vote-blue

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          env:
            - name: VOTE_VERSION
              value: "BLUE"

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT

          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
